# Generated by Django 3.0.2 on 2020-01-23 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('D', 'dog'), ('C', 'cat')], default='D', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('B', 'breed'), ('M', 'mix')], default='B', max_length=1),
            preserve_default=False,
        ),
    ]
