# Generated by Django 3.0.2 on 2020-01-24 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200123_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='test-prod'),
            preserve_default=False,
        ),
    ]
