# Generated by Django 3.0.2 on 2020-01-24 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200124_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discountedprice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
    ]
