# Generated by Django 3.0.2 on 2020-01-25 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200124_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='\this is a exquisitely cute pup which blsh blsh blsh blsh blhs'),
            preserve_default=False,
        ),
    ]
