# Generated by Django 3.0.2 on 2020-02-22 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200222_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='recieved',
            new_name='received',
        ),
    ]
